### ISSUE TITLE
looking at a bug in the Version: 0.52.3-1~precise

### ISSUE THREAD

**Issue by mikelynn2** [crate/crate-admin#173]
looking at a angularjs error in the console.  blank screen for me

Uncaught Error: [$injector:modulerr] Failed to instantiate module crate due to:
Error: [$injector:modulerr] Failed to instantiate module truncate due to:
Error: [$injector:nomod] Module 'truncate' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.3.15/$injector/nomod?p0=truncate
    at http://10.3.12.3:4200/_plugin/crate-admin/scripts/21417c0c.angular.js:1:412
    at http://10.3.12.3:4200/_plugin/crate-admin/scripts/21417c0c.angular.js:1:8758

**Comment by mikethebeer** [comment]
Hi @mikelynn2 ,

thanks for the report. A fix https://github.com/crate/crate-admin/commit/d6e953b5d1db5edd949dc0559487bbe7744c5d5f is already available in crate-admin 0.15. A new Crate version will be available soon.

**Comment by mikethebeer** [comment]
Fix is in Crate 0.52.4 stable
https://github.com/crate/crate/releases/tag/0.52.4
