### ISSUE TITLE
0.54.3 version shows cluster as yellow with underrepl shards during shard relocation

### ISSUE THREAD

**Issue by reversefold** [crate/crate-admin#178]
The `/_cluster/health` API shows the cluster status as green but the crate-admin shows the status as yellow with underreplicated shards. When I click through to the tables it shows underreplicated shards on some tables. This was after an upgrade from 0.51.6 to 0.54.3 on a copy of our production cluster with 4 billion records and it took more than 10 minutes for the crate-admin to show a green state.

I was hitting `/_cluster/health` on the same system as I was viewing the crate-admin on.

I was also watching the `/_cat/shards` endpoint and there were no unassigned or initializing shards when the `/_cluster/health` API was showing green. However, there were relocating shards and as soon as there were no relocating shards the crate-admin showed green as well, so it looks like the crate-admin is incorrectly marking relocating shards as underreplicated.

**Comment by chaudum** [comment]
hi @reversefold 
while investigating this issue in the admin ui, we discovered that we actually do not expose the correct shard state information in the sys.shards table. we're discussing right now how to handle that and will come up with a solution asap.
we also found [another issue](https://github.com/crate/crate-admin/commit/ad7cfe32e45a4eefe4af422848d98c88f563eae2) which has been fixed already and will be available with the next hotfix.

**Comment by reversefold** [comment]
Glad I'm helping to find these issues.

**Comment by joemoe** [comment]
@reversefold we fixed this. it will be released in the next couple of days with 0.54.5.

**Comment by reversefold** [comment]
Seems to be fixed.
