### ISSUE TITLE
Admin UI hangs when running in background window/tab for a longer time

### ISSUE THREAD

**Issue by chaudum** [crate/crate-admin#210]
When the UI is running in the background for a longer time it tends to hang when brought into focus again, sometimes resulting in an unresponsive browser tab/window. This can be caused by the amount of AJAX requests made and also by the graphs on the overview and node detail pages.

A possible solution would be to pause performing requests whenever the admin ui runs in the background. This can be detected using the [Page Visibility API](https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API?redirectlocale=en-US&redirectslug=DOM%2FUsing_the_Page_Visibility_API).
##

**Comment by seut** [comment]
This bug report is quite old and may not be valid anymore. If the observed behaviour still occur, please reopen.
