### ISSUE TITLE
copile the code when run in this code？

### ISSUE THREAD

**Issue by jinhang** [crate/crate-admin#219]
```
patches = ${buildout:directory}/patches/0001-change-python-references-to-python2.patch
patch-options = -p1
```
![image](https://cloud.githubusercontent.com/assets/4497831/18630192/663860ac-7e9d-11e6-930f-74acaef9ae5a.png)

**Comment by chaudum** [comment]
hi @jinhang 
the patch provided is a fix to be able to compile nodejs in the buildout using both python2 and python3
we haven't tested the admin-ui development setup on windows yet.

can you try to remove these 2 lines?

also, if you have nodejs/npm/bower installed on your local machine, you can simply remove them from the parts in `buildout.cfg`

**Comment by jinhang** [comment]
thanks a lot ,I have compile successed.and hava a folder dist,but if I want insert some div code in *.html to expand other function.
Is is ture?

**Comment by chaudum** [comment]
@jinhang I don't quite understand your question.
for development you just run the dev server:
`bin/grunt server` -> starts development server
and to build the project:
`bin/grunt build` -> compiles sources into dist folder

**Comment by jinhang** [comment]
thanks a lot
