### ISSUE TITLE
logo url throws off urlPattern

### ISSUE THREAD

**Issue by brennv** [crate/crate-admin#236]
Clicking the logo loads a page with empty data at: 
http://localhost:4200/_plugin/crate-admin/index.html#

Then clicking on the Overview button returns empty data at:
http://localhost:4200/_plugin/crate-admin/index.html#/
##

**Comment by chaudum** [comment]
@brennv thanks for reporting, we'll have a look! however, if you are eager to contribute a fix we'd be happy 🙂

**Comment by chaudum** [comment]
hi @brennv 
this fix has been released with the latest version of admin-ui and is available with the current crate version (0.56).
