### ISSUE TITLE
Console Page Error

### ISSUE THREAD

**Issue by foreachsky** [crate/crate-admin#248]
i upgrade crate version from 0.54 to 0.56.2

when i open then console page , excete sql ,the page is error
error msg:
![error](https://cloud.githubusercontent.com/assets/8233336/19545668/b2fdd112-96ba-11e6-882c-bbb5a0980753.png)
##

**Comment by chaudum** [comment]
hi @foreachsky 
a fix for this issue has already been applied on master and will be available with the next 0.56 hotfix release.
https://github.com/crate/crate-admin/issues/244
