### ISSUE TITLE
TABLES View shows 0 tables

### ISSUE THREAD

**Issue by mikethebeer** [crate/crate-admin#251]
Because of following error 0 tables are shown in `TABLES` view:

```
error:
{message: "SQLActionException[ColumnUnknownException: Column table_schema unknown]", code: 4043}
```

Crate Version `0.57.0`
Crate Admin `0.21.0`

Statement that causes the error:

``` sql
SELECT table_name, table_schema, format('%s.%s', table_schema, table_name) AS fqn, _node['id'] AS node_id, state, routing_state, relocating_node, count(*), "primary", sum(num_docs), avg(num_docs), sum(size) FROM sys.shards GROUP BY table_name, table_schema, fqn, node_id, state, routing_state, relocating_node, "primary";
```

Caused by: https://github.com/crate/crate-admin/commit/e093c0e002d86256c2b3eceeb3db931b7cfb0070
##

**Comment by celaus** [comment]
What versions of CrateDB and crate-admin? it seems to work fine on play.crate.io :)
