### ISSUE TITLE
Query console error with double quotes

### ISSUE THREAD

**Issue by bputt** [crate/crate-admin#305]
When issuing a query from the console using double quotes, I'll get a NULL Exception. If I change it to single quotes, it runs correctly. Is the UI supposed to handle that properly or are we not supposed to use double quotes?

This fails
```
SELECT * FROM table WHERE id = "someId" limit 100;
```

This does not fail
```
SELECT * FROM table WHERE id = 'someId' limit 100;
```

**Comment by chaudum** [comment]
hi @bputt !
what is your column data type (I assume STRING)? string literals require single quotes; double quotes are for identifiers -- https://crate.io/docs/reference/sql/reference/lexical_structure.html

however, even when using double quotes it should not throw a NPE. Can you please paste the full stacktrace of the query as well as your table schema.

**Comment by bputt** [comment]
After further testing, it doesn't throw a NPE, so recommending to close
