### ISSUE TITLE
[Feature] Resizable table overview

### ISSUE THREAD

**Issue by nook24** [crate/crate-admin#428]
**Use case:** Add a resize method to the tables overview of Crate Admin UI

**Feature description:**
At the moment the width of the table overview in Admin UI is hardcoded to `250px` in Version 1.1.2.
So for longer table names, the status of the table is hidden, so would be nice to make this resizable
![bildschirmfoto 2017-05-15 um 11 42 15](https://cloud.githubusercontent.com/assets/9019992/26051811/a70878a2-3963-11e7-94a7-9780d1eece67.png)

**Comment by joemoe** [comment]
thanks for reporting @nook24. we will improve that i'll keep you up to date.

**Comment by m-kharbat** [comment]
I'm closing this issue, since it was fixed by doing a word break
<img width="249" alt="screen shot 2018-07-16 at 15 57 57" src="https://user-images.githubusercontent.com/13311684/42762656-21120336-8911-11e8-8744-6585d4bcb702.png">
