### ISSUE TITLE
tree view identifies null-values as objects (e.g. on string column) 

### ISSUE THREAD

**Issue by floggi83186** [crate/crate-admin#486]
Display Error in "Object Tree View"
====

I stumbled across an display error in the admin ui.

Steps to reproduce (crate version: 2.1.7)
----

Create Table

```sql
CREATE TABLE IF NOT EXISTS "doc"."bug" (
   "test" OBJECT (strict) AS (
      "text" STRING
   ),
   "text" STRING
);
```
And then insert some data

```sql
insert into bug (test,text) values ({text='test'}, 'test');
insert into bug (test,text) values ({text='null'}, 'null');
insert into bug (test,text) values ({text=null}, null);
```

"Display Error":

The last statement inserts null values, and this value is represented as an object in the tree-view.

```sql
select * from bug limit 100;
```

![image](https://user-images.githubusercontent.com/22588878/31605816-941ac268-b267-11e7-94f3-9119f1ea58b0.png)

**Comment by m-kharbat** [comment]
Thank you for reporting we will look into it
