### ISSUE TITLE
Filter of tables shows weird results

### ISSUE THREAD

**Issue by nook24** [crate/crate-admin#535]
I noticed, that the filter of tables return some tables, that doesn't match the filter string.
Here are a few examples:
Filter for `services` returns `statusengine_tasks` and `openitcockpit_commands` (which even don't contain a column named `services`)
![bildschirmfoto 2018-02-13 um 09 11 42](https://user-images.githubusercontent.com/9019992/36153558-ee92e462-10ce-11e8-8da2-70ab6c78e3cb.png)

Example 2:
![bildschirmfoto 2018-02-13 um 09 11 36](https://user-images.githubusercontent.com/9019992/36153564-f5c3f6ea-10ce-11e8-82b0-0aab53d9bf9f.png)

Example 3:
![bildschirmfoto 2018-02-13 um 09 11 47](https://user-images.githubusercontent.com/9019992/36153569-f9283d00-10ce-11e8-8f65-462292196d06.png)

**CrateDB version**: 2.3.2

**JVM version**:
java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)

**OS version / environment description**:
Ubuntu Xenial, Ubuntu Trusty

**Steps to reproduce**:
Create tables and use the filter

**Comment by joemoe** [comment]
hi @nook24, thanks for reporting. we will look into that.

**Comment by m-kharbat** [comment]
This issue is fixed. The fix will be in the next minor 2.3 release
