### ISSUE TITLE
Clicked Table doesnt show the Table

### ISSUE THREAD

**Issue by m4ximum** [crate/crate-admin#560]
Hi there, 
it seems like the Filtering of Tables described in #535 seems to work now in Crate 2.3.6 but I have noticed that the link to the tables are still completely wrong. 

As You can see here if I search for "host" Tables and click on statusengine_hoststatus I get the "openitcockpit_contacts" Table. 

Filtered List
![broken](https://user-images.githubusercontent.com/9554776/38861213-4660c166-4232-11e8-8441-add2bcf768d1.png)

When I remove the Filter (the reset filter button in the input field is also not working) you can see the original order of all tables. Seems to me like the links of the filtered list is still in the order as the unfiltered list so everything that is on position 1 after filtering get the link to the table at position 1 in the unfiltered list. 

Unfiltered List
![bildschirmfoto 2018-04-17 um 11 30 09](https://user-images.githubusercontent.com/9554776/38861409-ccdd4598-4232-11e8-8ea4-cc88b1dfe358.png)

Filtered List
![broken2](https://user-images.githubusercontent.com/9554776/38862015-2aad6c10-4234-11e8-9321-e73f182b2989.png)

Browser: Firefox 59.0.2 
Crate: 2.3.6

**Comment by m-kharbat** [comment]
Thank you for reporting @m4ximum, we'll look into this.

**Comment by Autophagy** [comment]
@m4ximum Thanks for giving us a heads up about this! This has been fixed, and will be in the next crate-admin release.
