### ISSUE TITLE
What is the default Admin UI login username and password?

### ISSUE THREAD

**Issue by aaamitsingh** [crate/crate-admin#606]
What is the default Admin UI login username and password?

**Comment by RomanMeingassner** [comment]
Hi @aaamitsingh, did you create a User? To be honest, I need a bit more context information to get you an answer. Looking forward to your reply!

**Comment by RomanMeingassner** [comment]
@aaamitsingh I haven't heard back from you on the issue, so I will close the issue for now. Don't hesitate to contact us again with a bit more context!
