### ISSUE TITLE
Wrong display of column value for nested partition key column

### ISSUE THREAD

**Issue by shm-dmitry** [crate/crate-admin#657]
Crate version: 4.0.10

*Steps to reproduce*

```
CREATE TABLE test
(
    pk object as (
        id string,
        part string
    ),
    PRIMARY KEY (pk['id'], pk['part'])
)
PARTITIONED BY (pk['part']);
>> (success)

insert into test (pk) values ( { id='1', part='x' } ) ;
>> (success)
```

Error marked on screenshots by red arrows:

1. In 'table view' does not showed partition key value:
![image1](https://user-images.githubusercontent.com/19342331/72256400-2bcb1300-361a-11ea-8a3e-247479aaee32.png)

2. In 'Query view' does not showed partition key value when column viewed as nested column.
But when I query column value directly - all data showed.
![image2](https://user-images.githubusercontent.com/19342331/72256411-31285d80-361a-11ea-8d9e-8010954b2855.png)

**Comment by mfussenegger** [comment]
Thank you for the report. We'll have a closer look at it.
