### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by msbt** [crate/crate-admin#668]
###  Documentation feedback

 
- Page title: The CrateDB Admin UI
- Page URL: https://crate.io/docs/crate/admin-ui/en/latest/index.html
- Source: https://github.com/crate/crate-admin/blob/master/docs/index.rst

---

just did a quick check on the docs and found some issues: 

- the `community edition` (probably wrong href) and 3 `enterprise only` links are broken (target https://crate.io/docs/crate/reference/en/latest/enterprise/index.html)
- the anchor for "Cluster name" is not available https://crate.io/docs/reference/configuration.html#cluster-name

**Comment by mechanomi** [comment]
thanks for reporting this issue, @msbt! someone from the @crate/docs team will update you here when this is fixed
