### ISSUE TITLE
Admin UI screenshot is out of date

### ISSUE THREAD

**Issue by mechanomi** [crate/crate-admin#670]
###  Documentation feedback

 
- Page title: The CrateDB Admin UI
- Page URL: https://crate.io/docs/crate/admin-ui/en/latest/index.html
- Source: https://github.com/crate/crate-admin/blob/master/docs/index.rst

---

the screenshot is out of date

**Comment by infoverload** [comment]
https://github.com/crate/crate-admin/issues/668

**Comment by infoverload** [comment]
Done
