### ISSUE TITLE
UI jumps to Tables view when using console 

### ISSUE THREAD

**Issue by faymarie** [crate/crate-admin#700]
Dear Craties, 

our team noticed a UI glitch when using the UI console. When working on a query in the console view, the interface frequently jumps back to displaying the first table of the first schema in the "Tables view". We observed this behaviour when working on queries related to subordinate schemas. 

This seems to be unrelated to the query itself. It occurs before and also while editing the query in the UI console, but not after the query was executed. This is especially inconvenient when longer queries get lost.

While editing a query in the console:
![Screenshot 2020-11-24 at 14 00 22](https://user-images.githubusercontent.com/32742984/100099112-43d90900-2e5f-11eb-8f67-7128d523d02e.png)

It jumps to this table view, like here:
![Screenshot 2020-11-24 at 14 04 16](https://user-images.githubusercontent.com/32742984/100098348-38391280-2e5e-11eb-8d64-d5230a8c09a3.png)

**CrateDB Version: 4.2.6**

**Comment by amotl** [comment]
Hi Marie and Naomi,

I tried to track this down and found #304 and #311. There is even a video which tries to explain the rationale for this fix at https://recordit.co/hU5WEMAANc. However, I can't make any sense of it.

I believe the code isn't needed anymore as it also works well without, at least from my perspective.

With kind regards,
Andreas.

**Comment by amotl** [comment]
I think the problem got fixed, so I am closing this issue now. Feel free to reopen if you see fit.
