### ISSUE TITLE
Bundle fonts within the crate distribution

### ISSUE THREAD

**Issue by rgl** [crate/crate-admin#758]
Currently, the fonts are being fetched from google fonts (https://fonts.googleapis.com/css?family=Open+Sans) in:

https://github.com/crate/crate-admin/blob/main/app/styles/vars/_typography.scss#L1

Can this be changed to bundle the font instead of depending on a external address? This is especially useful when self-hosting crate without internet access (this ends up delaying the entire loading of admin ui until the font css request timeouts).

**Comment by amotl** [comment]
Dear Rui,

thank you for writing in and apologies for the late reply. We will take your suggestion into account on behalf of the next development iteration. At the same time, we are always happy about patches from the community.

With kind regards,
Andreas.

/cc @msbt

**Comment by msbt** [comment]
Sure thing @amotl, will check it out next week!

**Comment by amotl** [comment]
Dear Rui,

@msbt submitted a patch to improve the situation with #770. The improvement will land in the next release. Thank you again!

With kind regards,
Andreas.
