### ISSUE TITLE
Links pointing to Crate.io 

### ISSUE THREAD

**Issue by michaelkremmel** [crate/crate-admin#819]
Hi,
I've realized that some links in the admin UI point to crate.io. Since the domain was moved to cratedb.com, it would be great to change those links at some point (now all of them are redirected correctly). I've also added some proposals to change some of the corresponding copy:

In the section **/help**
![grafik](https://github.com/crate/crate-admin/assets/74347398/6a32ac22-ed99-4de6-a1c1-bb61cea45345)

<table>
<tr><td>Existing</td><td>New</td><tr>
<tr><td>Ask Crate.io engineers in our Discourse community.</td><td>Join our community to get answers to your technical questions and discuss other topics.</td><tr>
<tr><td>https://community.crate.io</td><td>https://community.cratedb.com</td><tr>
<tr><td></td><td></td><tr>
<tr><td>https://crate.io/docs/</td><td>https://cratedb.com/docs/crate/reference/en/latest/</td><tr>
<tr><td></td><td></td><tr>
<tr><td>Enterprise support</td><td>Support plans</td><tr>
<tr><td>For enterprise support, please check our pricing page.</td><td>Get assistance from our engineering team. Check our support plans.</td><tr>
<tr><td>https://crate.io/enterprise/</td><td>https://crate.io/product/pricing/support-plans </td><tr>
</table>

When clicking the **cogwheel**
![grafik](https://github.com/crate/crate-admin/assets/74347398/c96aaae0-f2f3-4f89-ac3b-e2e189cedd8d)

<table>
<tr><td>Existing</td><td>New</td><tr>
<tr><td>https://crate.io/docs/en/5.4/ </td><td>https://cratedb.com/docs/crate/reference/en/5.4</td><tr>
<tr><td></td><td></td><tr>
<tr><td>Schedule a call with a Crate.io engineer</td><td>Schedule a call with a CrateDB engineer</td><tr>
<tr><td>https://crate.io/demo?utm_source=adminui&utm_medium=browser&utm_term=&utm_content=demolink&utm_campaign=newsfeed&ajs_event=clicked_demo_link </td><td>https://cratedb.com/contact </td><tr>
<tr><td></td><td></td><tr>
<tr><td>https://crate.io/blog/</td><td>https://cratedb.com/blog </td><tr>
</table>

**Comment by amotl** [comment]
Hi Michael,

GH-822 and GH-823 bring in the requested adjustments, and a bit more copy-editing.

For changing texts, you would need to provide corresponding translations into all available languages. Those would be the corresponding text fragments you've provided:

- Join our community to get answers to your technical questions and discuss other topics.
- Support plans.
- Get assistance from our engineering team. Check our support plans.

With kind regards,
Andreas.

**Comment by michaelkremmel** [comment]
Hi Andreas, Thanks for letting me know. How do you normally deal with translation? Is there a process for that? Or should I just ask Craties who are native speakers of those languages to help me out on that front?

**Comment by amotl** [comment]
Yeah, that's the spirit.

**Comment by michaelkremmel** [comment]
Here you go @amotl 

<table>
<tr>
<td>EN</td>
<td>DE</td>
<td>ES</td>
<td>FR</td>
<td>IT</td>
</tr>
<tr>
<td>Join our community to get answers to your technical questions and discuss other topics.</td>
<td>Tausche dich mit CrateDB Nutzern und Entwicklern aus, um Antworten zu deinen Fragen zu erhalten.</td>
<td>Únete a nuestra comunidad para obtener respuesta a tus preguntas técnicas y debatir otros temas.</td>
<td>Rejoignez notre communauté pour obtenir des réponses à vos questions techniques et discuter d'autres sujets.</td>
<td>Unisciti alla nostra community per ottenere risposte alle tue domande tecniche e confrontarti su vari temi.</td>
</tr>
<tr>
<td>Support plans</td>
<td>Support Angebot</td>
<td>Planes de soporte</td>
<td>Plans de soutien</td>
<td>Piani di supporto</td>
</tr>
<tr>
<td>Get assistance from our engineering team. Check our support plans.</td>
<td>Alles zum professionellen Support durch unser Technik-Team.</td>
<td>Obtén asistencia de nuestro equipo de ingenieros. Consulta nuestros planes de soporte.</td>
<td>Obtenez l'assistance de notre équipe d'ingénieurs. Consultez nos plans d'assistance.</td>
<td>Ottieni assistenza dal nostro team di ingegneri. Consulta i nostri piani di supporto.</td>
</tr>
</table>

**Comment by amotl** [comment]
Thank you. I've just submitted GH-826 to bring them in.

**Comment by amotl** [comment]
Hi again. This has been released and it will be part of the next release of CrateDB. In the meanwhile, you can test it by running CrateDB nightly.

```shell
docker run --rm -it --name=cratedb --publish=4200:4200 --publish=5432:5432     --env=CRATE_HEAP_SIZE=4g crate/crate:nightly     -Cdiscovery.type=single-node
```

Then, navigate to the help page.

http://localhost:4200/#!/help

**Comment by amotl** [comment]
Hi again. I think this can be considered resolved. Feel free to re-open when applicable.
