### ISSUE TITLE
Consider removing --openssl-legacy-provide

### ISSUE THREAD

**Issue by neon0404** [crate/crate-admin#846]
As far as i remember, `NODE_OPTIONS=--openssl-legacy-provider` was used to satisfy `webpack@4`
Current webpack version doesn't require this argument

Currently `package.json` is incompatible with Windows due to a different way of setting environment variables
```json
  "scripts": {
    "cratedb": "docker run -it --rm --publish 4200:4200 crate/crate:nightly -Chttp.cors.enabled=true -Chttp.cors.allow-origin=*",
    "develop": "NODE_OPTIONS=--openssl-legacy-provider webpack serve --progress --config=webpack.dev.config.js --open-target=http://localhost:9000/?base_uri=http://localhost:4200#!/",
    "build": "NODE_OPTIONS=--openssl-legacy-provider webpack --config webpack.prod.config.js --progress",
    "test": "NODE_OPTIONS=--openssl-legacy-provider karma start"
  }
```

Tested without it - works fine, should PR?

**Comment by amotl** [comment]
Hi @neon0404,

please submit a PR. If that doesn't break anything on our end, we will be happy to accept it.

With kind regards,
Andreas.
